name: bhavsarv1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1

  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # Form & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, uncomment and modify the below section:
  # assets:
  #   - images/

  # For custom fonts, uncomment and configure this section:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
